In [1]:
import numpy as np

In [33]:
a = np.array([0,0.1,0.2,0.3])
b = np.array([5,6,1,2])

c = a[:, None] - b[:]

print(c)
a_idx, b_idx = np.unravel_index(np.argmin(c), c.shape)

print(a_idx, b_idx)
print(a[a_idx], b[b_idx])

[[-5.  -6.  -1.  -2. ]
 [-4.9 -5.9 -0.9 -1.9]
 [-4.8 -5.8 -0.8 -1.8]
 [-4.7 -5.7 -0.7 -1.7]]
0 1
0.0 6
